"""Data Utilities.

This file provides utility functions for reading, writing and verifying the integrity of binary
files generated by the sensor network. Files are in a custom binary format.

This file is a part of the Wireless Sensor Network project.
(c) Copyright 2020 Jacob Larkin and Adriann Liceralde
"""

import binascii
import numpy as np



def compute_checksum(file_object, chunk_size=65536) -> int:
    """Compute and return checksum (CRC32) of given bytes."""
    prev = 0
    while True:
        chunk = file_object.read(chunk_size)
        if not chunk:
            break
        prev = binascii.crc32(chunk, prev)
    return "%08X" % (prev & 0xFFFFFFFF)


def load_file(filename: str) -> np.array:
    """Load the given file, verify integrity, and return as a numpy array."""


def verify_integrity(file_object):
    """Verify the integrity of the given file object. Throw exceptions on bad files."""
