/*Data Utilities.

This file provides utility functions for reading, writing and verifying the integrity of binary
files generated by the sensor network. Files are in a custom binary format.

This file is a part of the Wireless Sensor Network project.
(c) Copyright 2020 Jacob Larkin and Adriann Liceralde
*/

#ifndef DATA_UTILS_H
#define DATA_UTILS_H

#include <stdint.h>
#include <stddef.h>


uint32_t crc32_update(uint32_t crc, uint8_t data);

uint32_t crc32_ascii(char *s);

uint32_t crc32_bytes_update(uint32_t crc, void* buffer, uint32_t length);


#endif
